# name="dev-imgz-next"
# pages_build_output_dir = "/.vercel/output/static"
# compatibility_date = "2024-07-25"

name = "dev-imgz-next"
# pages_build_output_dir = "./.next/server/pages"
pages_build_output_dir = "./.vercel/output/static"
# node_compat = true
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "WORDS"
id = "<YOUR_ID>"
preview_id = "<YOUR_ID>"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-yeniseysk"
database_id = "<YOUR_ID>"
preview_database_id = "<YOUR_ID>" # Required for Pages local development
